apiVersion: v1
kind: Service
metadata:
  name: simple-headless
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: simple
  ports:
    - protocol: TCP
      port: 9898
      targetPort: 9898