apiVersion: v1
kind: Service
metadata:
  name: simple-node-port
spec:
  type: NodePort
  selector:
    app: simple
  ports:
    - protocol: TCP
      port: 9898
      targetPort: 9898
      nodePort: 30000