apiVersion: v1
kind: Pod
metadata:
  name: readiness-pod
spec:
  containers:
  - name: readiness-pod
    image: stefanprodan/podinfo
    readinessProbe:
      httpGet:
        path: /readyz
        port: 9898
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      failureThreshold: 3
      timeoutSeconds: 1