apiVersion: v1
kind: Pod
metadata:
  name: cm-vol-pod
spec:
  containers:
  - name: cm-vol-pod
    image: stefanprodan/podinfo
    env:
    - name: PODINFO_CONFIG_PATH
      value: /config/
    volumeMounts:
    - mountPath: /config/input.json
      name: config
      subPath: input.json
  volumes:
  - name: config
    configMap:
      name: file-cm