apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simple
  name: volume
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple
  template:
    metadata:
      labels:
        app: simple
    spec:
      containers:
      - name: simple-pod
        image: stefanprodan/podinfo
        volumeMounts:
        - mountPath: /data/
          name: data
      volumes:
      - name: data
        hostPath:
          path: /home/docker/persistent-volume/
          type: Directory