apiVersion: v1
kind: Pod
metadata:
  name: hp-vol-pod
spec:
  containers:
  - name: hp-vol-pod
    image: stefanprodan/podinfo
    env:
    - name: PODINFO_CONFIG_PATH
      value: /config/
    volumeMounts:
    - mountPath: /config/
      name: config
  volumes:
  - name: config
    hostPath:
      path: /home/docker/config/