apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simple
  name: simple-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple
  template:
    metadata:
      labels:
        app: simple
    spec:
      containers:
      - name: simple-pod
        image: stefanprodan/podinfo2